### ISSUE TITLE
问下这个东西怎么用呢？

### ISSUE THREAD

**Issue by yanyinxi** [seajs/seamap#2]
问下这个东西怎么用呢？

我下载了，
点击了， seamap.crx
并且 在chrome下 点开了seamap-master\src\popup.html  点击了refresh 按钮， 没有任何反应啊。

**Comment by army8735** [comment]
在扩展插件页面中打开、安装。在有seajs的页面点击才有用

**Comment by yanyinxi** [comment]
我的没有反应啊！

![qq20140611144348](https://cloud.githubusercontent.com/assets/7278503/3240834/9e394344-f133-11e3-9487-506b2bacbdf4.jpg)

**Comment by yanyinxi** [comment]
我注释 // var test = require('../test') 

还是不行啊

**Comment by army8735** [comment]
下spm2版本

**Comment by yanyinxi** [comment]
是我人品有问题吗？

我的 spm -V            2.2.6

**Comment by yanyinxi** [comment]
@army8735    请看下我的这个，我自己测试没有有向图！

不知道是什么原因？
https://github.com/yanyinxi/seajsMakeDigraph

**Comment by army8735** [comment]
我调试看看，运行了，在body上生成了数据，console能看到，但是绘制有问题

**Comment by army8735** [comment]
好了

**Comment by yanyinxi** [comment]
@army8735  特别感谢， 已测试，没有问题了。

**Comment by yanyinxi** [comment]
建议能不能把路径缩短点，让箭头指的更近点！看起来更美观点，不然都看不清楚。。。
![qq20140612075619](https://cloud.githubusercontent.com/assets/7278503/3252692/51bc9d70-f1c6-11e3-9990-5d5bc4655f7d.jpg)

**Comment by army8735** [comment]
那是相对于base的，太深的话就这样，我也想不到好办法
